loop_hz: 30.0
yaw: 0.0

high_threshold: 0.93
mid_threshold: 0.85
low_threshold: 0.80

high_charge_time: 240.0
mid_charge_time: 180.0
low_charge_time: 120.0

high_time: 30.0
mid_time: 20.0
low_time: 10.0
